# 
# Synthesis run script generated by Vivado
# 

set_param project.vivado.isBlockSynthRun true
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xc7a200tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/vivado_project/8_pipeline_cpu/8_pipeline_cpu.cache/wt [current_project]
set_property parent.project_path D:/vivado_project/8_pipeline_cpu/8_pipeline_cpu.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/vivado_project/8_pipeline_cpu/8_pipeline_cpu.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_ip -quiet D:/vivado_project/8_pipeline_cpu/8_pipeline_cpu.srcs/sources_1/ip/inst_rom/inst_rom.xci
set_property is_locked true [get_files D:/vivado_project/8_pipeline_cpu/8_pipeline_cpu.srcs/sources_1/ip/inst_rom/inst_rom.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top inst_rom -part xc7a200tfbg676-2 -mode out_of_context

rename_ref -prefix_all inst_rom_

write_checkpoint -force -noxdef inst_rom.dcp

catch { report_utilization -file inst_rom_utilization_synth.rpt -pb inst_rom_utilization_synth.pb }

if { [catch {
  file copy -force D:/vivado_project/8_pipeline_cpu/8_pipeline_cpu.runs/inst_rom_synth_1/inst_rom.dcp D:/vivado_project/8_pipeline_cpu/8_pipeline_cpu.srcs/sources_1/ip/inst_rom/inst_rom.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub D:/vivado_project/8_pipeline_cpu/8_pipeline_cpu.srcs/sources_1/ip/inst_rom/inst_rom_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub D:/vivado_project/8_pipeline_cpu/8_pipeline_cpu.srcs/sources_1/ip/inst_rom/inst_rom_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim D:/vivado_project/8_pipeline_cpu/8_pipeline_cpu.srcs/sources_1/ip/inst_rom/inst_rom_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim D:/vivado_project/8_pipeline_cpu/8_pipeline_cpu.srcs/sources_1/ip/inst_rom/inst_rom_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir D:/vivado_project/8_pipeline_cpu/8_pipeline_cpu.ip_user_files/ip/inst_rom]} {
  catch { 
    file copy -force D:/vivado_project/8_pipeline_cpu/8_pipeline_cpu.srcs/sources_1/ip/inst_rom/inst_rom_stub.v D:/vivado_project/8_pipeline_cpu/8_pipeline_cpu.ip_user_files/ip/inst_rom
  }
}

if {[file isdir D:/vivado_project/8_pipeline_cpu/8_pipeline_cpu.ip_user_files/ip/inst_rom]} {
  catch { 
    file copy -force D:/vivado_project/8_pipeline_cpu/8_pipeline_cpu.srcs/sources_1/ip/inst_rom/inst_rom_stub.vhdl D:/vivado_project/8_pipeline_cpu/8_pipeline_cpu.ip_user_files/ip/inst_rom
  }
}
